// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgqlhnnobatcsbpskmdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhncWxobm5vYmF0Y3NicHNrbWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0ODg0ODIsImV4cCI6MjA1NDA2NDQ4Mn0.PSDcAo_c4sn-kBy6sVDpoF5k63AhqUqWs6Jp1pZAzWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);